

spring:
  application:
    name: shareMidi_api

  datasource:
    url: jdbc:postgresql://localhost:5432/shareMidi
    username: postgres
    password: postgress
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

